{"name": "test_redis", "status": "broken", "statusDetails": {"message": "redis.exceptions.ResponseError: wrong number of arguments for 'hdel' command", "trace": "def test_redis():\n        logger.info(\"开始执行===>\")\n        pool = redis.ConnectionPool(host=\"192.168.4.4\", port=6379, password=\"0.123abc\", db=0)\n        r = redis.Redis(connection_pool=pool)\n        logger.info(\"r is the redis===>{}\".format(r))\n        logger.info(\"dbsize is===>{}\".format(r.dbsize()))\n        # logger.info(\"hash is ==>\".format(r.hgetall(\"pookie:token:user_230\")))\n        logger.info(\"All keys of tokens is ===>{}\".format(r.hkeys(\"pookie:tokens:user_1346\")))\n        logger.info(\"All keys of token is ===>{}\".format(r.get(\"pookie:token:user_1346\")))\n        r.delete(\"pookie:token:user_1346\")\n>       r.hdel(\"pookie:tokens:user_1346\")\n\nredis_operate.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../venv/lib/python3.7/site-packages/redis/client.py:3002: in hdel\n    return self.execute_command('HDEL', name, *keys)\n../venv/lib/python3.7/site-packages/redis/client.py:901: in execute_command\n    return self.parse_response(conn, command_name, **options)\n../venv/lib/python3.7/site-packages/redis/client.py:915: in parse_response\n    response = connection.read_response()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Connection<host=192.168.4.4,port=6379,db=0>\n\n    def read_response(self):\n        \"Read the response from a previously sent command\"\n        try:\n            response = self._parser.read_response()\n        except socket.timeout:\n            self.disconnect()\n            raise TimeoutError(\"Timeout reading from %s:%s\" %\n                               (self.host, self.port))\n        except socket.error as e:\n            self.disconnect()\n            raise ConnectionError(\"Error while reading from %s:%s : %s\" %\n                                  (self.host, self.port, e.args))\n        except BaseException:\n            self.disconnect()\n            raise\n    \n        if self.health_check_interval:\n            self.next_health_check = time() + self.health_check_interval\n    \n        if isinstance(response, ResponseError):\n>           raise response\nE           redis.exceptions.ResponseError: wrong number of arguments for 'hdel' command\n\n../venv/lib/python3.7/site-packages/redis/connection.py:756: ResponseError"}, "attachments": [{"name": "log", "source": "ab7c31e3-4ecf-4b2c-b81a-9a25683adba1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f10a2876-b09d-4d05-b493-c51fea76e5a1-attachment.txt", "type": "text/plain"}], "start": 1636099060699, "stop": 1636099061141, "uuid": "a490f327-3b38-4f07-889c-9c6167082e79", "historyId": "2470b976c53a3ba91da07979e4d471a2", "testCaseId": "ccdebc5849e417ff9042ff98197e66c5", "fullName": "common.redis_operate#test_redis", "labels": [{"name": "parentSuite", "value": "common"}, {"name": "suite", "value": "redis_operate"}, {"name": "host", "value": "tongchunyan.local"}, {"name": "thread", "value": "65328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "common.redis_operate"}]}