{"name": "test_redis", "status": "broken", "statusDetails": {"message": "redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value", "trace": "def test_redis():\n        logger.info(\"开始执行===>\")\n        pool = redis.ConnectionPool(host=\"192.168.4.4\", port=6379, password=\"0.123abc\", db=0)\n        r = redis.Redis(connection_pool=pool)\n        logger.info(\"r is the redis===>{}\".format(r))\n        logger.info(\"dbsize is===>{}\".format(r.dbsize()))\n>       logger.info(\"hash is ==>\".format(r.hgetall(\"pookie:token:user_230\")))\n\nredis_operate.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../venv/lib/python3.7/site-packages/redis/client.py:3014: in hgetall\n    return self.execute_command('HGETALL', name)\n../venv/lib/python3.7/site-packages/redis/client.py:901: in execute_command\n    return self.parse_response(conn, command_name, **options)\n../venv/lib/python3.7/site-packages/redis/client.py:915: in parse_response\n    response = connection.read_response()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Connection<host=192.168.4.4,port=6379,db=0>\n\n    def read_response(self):\n        \"Read the response from a previously sent command\"\n        try:\n            response = self._parser.read_response()\n        except socket.timeout:\n            self.disconnect()\n            raise TimeoutError(\"Timeout reading from %s:%s\" %\n                               (self.host, self.port))\n        except socket.error as e:\n            self.disconnect()\n            raise ConnectionError(\"Error while reading from %s:%s : %s\" %\n                                  (self.host, self.port, e.args))\n        except BaseException:\n            self.disconnect()\n            raise\n    \n        if self.health_check_interval:\n            self.next_health_check = time() + self.health_check_interval\n    \n        if isinstance(response, ResponseError):\n>           raise response\nE           redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value\n\n../venv/lib/python3.7/site-packages/redis/connection.py:756: ResponseError"}, "attachments": [{"name": "log", "source": "9feeb306-527c-4f8a-b352-6f3ee275d59f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "db6ccd39-989c-422c-9c09-8aff2bf24ba4-attachment.txt", "type": "text/plain"}], "start": 1636098083516, "stop": 1636098083756, "uuid": "0f2d4eab-8451-41b6-bb02-a75a741a9339", "historyId": "2470b976c53a3ba91da07979e4d471a2", "testCaseId": "ccdebc5849e417ff9042ff98197e66c5", "fullName": "common.redis_operate#test_redis", "labels": [{"name": "parentSuite", "value": "common"}, {"name": "suite", "value": "redis_operate"}, {"name": "host", "value": "tongchunyan.local"}, {"name": "thread", "value": "64860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "common.redis_operate"}]}